services:
  details:
    build: .
    image: ghcr.io/iceevil4/bookinfo-details:dev
    ports:
      - "8081:8081"

  productpage:
    build: .
    image: ghcr.io/iceevil4/bookinfo-productpage:dev
    ports:
      - "8083:8083"
    environment:
      RATINGS_HOSTNAME: http://ratings:8080
      DETAILS_HOSTNAME: http://details:8081
      REVIEWS_HOSTNAME: http://reviews:8082

  ratings:
    build: .
    image: ghcr.io/iceevil4/bookinfo-ratings:dev
    ports:
      - "8080:8080"
    environment:
      SERVICE_VERSION: v2
      MONGO_DB_URL: mongodb://mongodb:27017/ratings
      MONGO_DB_USERNAME: ratings
      MONGO_DB_PASSWORD: CHANGEME
  mongodb:
    image: bitnami/mongodb:5.0.2-debian-10-r2
    volumes:
      - "./databases:/docker-entrypoint-initdb.d"
    environment:
      MONGODB_ROOT_PASSWORD: CHANGEME
      MONGODB_USERNAME: ratings
      MONGODB_PASSWORD: CHANGEME
      MONGODB_DATABASE: ratings

  reviews:
    build: .
    image: ghcr.io/iceevil4/bookinfo-reviews:dev
    ports:
      - "8082:9080"
    environment:
      RATINGS_SERVICE: http://ratings:8080
  